server:
  port: 7000
spring:
  cloud: 
    gateway:
      routes:
      - id: serv-vuelos
          #lb:// cuando se va a acceder a traves de Eureka
        uri: lb://servicio-vuelos #http://localhost:11000
        predicates:
          - Path=/svuelos/**
        filters:
          - RewritePath=/svuelos/*, /
        
      - id: serv-hoteles
          #lb:// cuando se va a acceder a traves de Eureka
        uri: lb://servicio-hoteles #http://localhost:8000
        predicates:
          - Path=/shoteles/**
        filters:
          - RewritePath=/shoteles/*, / #StripPrefix=1 o bien RewritePath=/shoteles(?<segment>/.*), ${segment} si 2.5+
        
      - id: serv-reservas
          #lb:// cuando se va a acceder a traves de Eureka
        uri: lb://servicio-reservas #http://localhost:10000
        predicates:
          - Path=/sreservas/**
        filters:
          - RewritePath=/sreservas/*, /
        
eureka:                  
  client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka
